### ISSUE TITLE
Replace (or add additional) button in UI to include ClusterToCSharpText directly

### ISSUE THREAD

**Issue by al-fisher** [BHoM/CSharp_Toolkit#6]
I suspect that most all users in the UI will want to go direct from Cluster to the C#Text.

Suggestion that the button (or another button) in the GH toolbar calls the conversion `ToCSharpText` for you. Removes the requirement to search for the other quite technical method.

![image](https://user-images.githubusercontent.com/15924573/72222350-a5e89280-355b-11ea-93d8-e05a20c7f013.png)

**Comment by adecler** [comment]
I agree it would be good to have the ToCSharpText component available in the menu but not too sure about making a single component out of the two. It might seems weird to have two components to do a single task at the moment but this is because the BHoM syntax tree is only used for that one thing. I very much intend to see that growing in the (near) future. 

With that in mind, it very much aligns with foundational philosophy of 
![image](https://github.com/BHoM/documentation/wiki/images/InteropA.png)

**Comment by al-fisher** [comment]
Yes - I see. Having both then makes sense. Cheers
